export const Routes = { 
    login: 'api/Users',
    getPieChart: 'api/Chart',
    getContra: 'api/Contra',
    postContra: 'api/PostContra',
    postUnMatch: 'api/UnMatched',
    getRecordsByStatus: 'api/Record',
    groupRecord: 'api/GroupRecord',
    getMatchedChart: 'api/Chart',
    getOpenChart: 'api/External',
    getGridInfo: 'api/GridInfo',
    manualPosting: 'api/ManualPosting',
    recoresults: 'api/recoresults',
    postMatch: 'api/Match',
    relationships: 'api/Relationships',
    ineternalAccount: 'api/IneternalAccount',
    addPost: 'api/Post',
    postEdit: 'api/PostEdit',
    postSplit: 'api/Split',
    addSplit: 'api/Split',
    getSplit: 'api/Split/',
    unGroup: 'api/UnGroup/',
    unGroupContra: 'api/UnGroupContra/',
    autoPost: 'api/AutoPosting/'
};
